[default.extend-words]
nin = "nin"
strat = "strat"
ND = "ND"
NUMER = "NUMER"
Chater = "Chater"
# Additional SciML terms
setp = "setp"
getp = "getp"
indexin = "indexin"
ists = "ists"
ispcs = "ispcs"
eqs = "eqs"
rhs = "rhs"
MTK = "MTK"