steps:
  - label: "{{matrix}}"
    matrix:
      - "Callbacks1"
      - "Callbacks2"
    env:
      GROUP: "{{matrix}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: true
    agents:
      os: "linux"
      queue: "juliaecosystem"
      arch: "x86_64"
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "Shadowing"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: true
          julia_args: "--threads=auto"
    agents:
      os: "linux"
      queue: "juliaecosystem"
      arch: "x86_64"
      exclusive: true
    env:
      GROUP: 'Shadowing'
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "Documentation"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project -e '
        println("--- :julia: Instantiating project")
        using Pkg
        Pkg.instantiate()
        Pkg.activate("docs")
        Pkg.instantiate()
        push!(LOAD_PATH, @__DIR__)
        println("+++ :julia: Building documentation")
        include("docs/make.jl")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      DATADEPS_ALWAYS_ACCEPT: true
    if: build.message !~ /\[skip docs\]/ && !build.pull_request.draft
    timeout_in_minutes: 1000

  - label: "Julia 1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
           coverage: false # 1000x slowdown
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: 'GPU'
    timeout_in_minutes: 60
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  SECRET_DOCUMENTER_KEY: "kn/go7E73O+gI4TGaPxQqsTYPi3eujNZ9rfygWhq+X0RUnwDL5YO8KPNRecGsVFB7UlZKfTsz1DfvhZmxAn4CBs7IWVwDpUjn5a2LmEUecwS0O/x55WM/ubsCdRuRT7trMkkTxmJDM5+hxEXaO5dtpHxydF/656lsRGUHGdiqUrso85W8Rg33HBIkBGQTli+Z9r0uT0E27rQndR4DZwSqag1g7jS89Tl0cSr21K89t+PmroI60f0fQvGRGQzf7xXO+0Es4KHu45F0LfHponoHE1zHgqljZfudPGkcL94jYhGzOh1FsMYPDs33aenIPWmccIql0ileTmwov2B/poM2A==;U2FsdGVkX19at/GymB5JQwKj745b+/T0aKQkZ+JtYy9IuqDQdVX/TtDoemiNC2e13QZMt5SvCM8+BXaQVWuYrxA6iGu2q+o0IqqQtTWNNvaHTlY7r0XpZjCUdZPXv0cdb+RYJY8WUjM92mdC6bMA+3dDyEslLyOCfWwAa7HrO8Ap6vmmMVWuGw8jkp2XWF2Tud+8mWmRaGK2UfECBtTPpgTrp8rDDgPX6GGueY50/g81yT8D+JDJq+hbrM3gx9zWTb/0TVpE6e4oyf8zwzODXzyBJqFnsoYB4IHD2+IHqzYmjZPqePy+/kzJC62qS5UgJ0W8fGclsqt5JyyYTd8yOP2bFe9NRvcoLiqlNQk2OfyKCdVCNPfCQWrwWOix7usryn33sjIuEBtAmI+3GzhZLr/PNFLGi4V/F/IfwujSRn6SDB6ahlQh3dNqIxPpPd/6NFYDcjJyANkXFRCU+6gAmj6hDlFlbpJwpBmMPRAuOewkARnCRHNSaybpi3bLzzgh9KhAToo4duJFKacaRckoR8Mt7O2zV7EBLx0ZLOmE/nDYyGbs3s4dsLrp7qYjxaUwWax3sv7Vw9Rxqt/7ibEhAqvAIIbDBg6Odyu036fiXrdzMRU2FsTtdxqNGZWqIqvN+S1+s9dCxi1SCuilh5otnariJ6VyOpkCcfB6r8XhSRGbDIWhAaZvPWGc28zTFyh0uzbN3vkwo5/KwFPjf/mrZv11S3HwCMB0P5UOzpbZVfNGSIA9gkahMS7LLIU06NdKcD8k3fFI0aruEd0JMkgfABLryVln4i7AUq9wdXBhD7XLapPS+VQckQUxYaFlzFPmeFVys4cMWwRsLnC8Adm6RWk/+fdfl0PupXOev2/TgeiIQZBC2TyEe3OUjZ0GeHYJFTq8ZsE+9oZQmYAnhI4OUe9SlsYqPYEcW5jk7aGc6XnAX/ZqNt9py+lo7h+anyFu4u3WAYyud1w4LK8tTsAmbvjefV/wuuJlRBs7Ic1gQTyiB1oP7/cy142RW1xeUPzM7XgvglBbst8E2Rn4h83KqqTGMCsI3Hzs8gCHhced0drDGsRLfXW0FIn2n2L088yhYjEjB+INj0YHBMJG3u6VYyETKeyaofkLzqJAs5l6FUr1sAP5gihZiTbc3Qw70SxlgR3ieP9feW1THfXqQTt/JhYC+eBTTcIJeeWN9pRssGzf6UanVd4Hek+PF99pmMMKdnNq6O5H20NwpXYuMAkbkxQ3DlwkbUdvQSVlX8aRAsKFwnILxBtSYlrhmavrnK4YDUIs/rV3t8By8EjYG3pj36mwS/MWqPxUJJTiBkxBXaSn15wTBN+IzBm+WBZXGQbZJivBSk7hFpRRzvRJSq6er/RDJ3TqVD9O5b2+p6EPdppz+RH3k2oF/zwYsTFqmj6OGerY1bVyYrWaafFEwGDVahELbZr63Igoff727i6aznDT4WXC5MHe3FQ8OlDSkm1bheRQCOBC61ET3xEA7nOtfFa6GSKSBecPL0rtW4SSewJK1t7z/awzEme9ZFIkDmbkZVhKc+bq6IEWuBUaMjtd5ClJmw03TfESNGWELbkVUPB8wGIZCCOX+FJX13p2d8tfHF6sJmDmfJ6weObVSEWUGHNwVny+ADK+4AojDYHfLOaRvhk3EsicHdXCWRRbjNWB1keRuRl0cahfrb5GSzKtacx4ooPLD4h1TanY/3ywnKjdIIlXxUJ1Z072NBYuzaxpr8tXPlt427vkMo2QOpZxiR6eHTokkrWrOGJ41QYpZfkovkyKWUH36FGNJVZEHBxMf3dOjqLTFzX/TRZ6HUVPv9xRl7SHgkPpaMXgCXIEA4A262i9HDpcZAYpMdqDdMp51ecY4mxS3AEZjU5xviDhfbyL/XXEdcHhL/UhoVuYZrdl3PZMKiNgk1LGWGY3NQEELFvUwRJW0rM9sGT/x2IbmfBzEOpbActI0QU7dsljAEGWTb9oudxCJoyEOB5COiTRJjeUXM+h5O4vgKPZ2jBLtf4IjRTdqNJ/C9hfTQgNwT8h0Bb2VoU0uiWD7gE4HZdMsrV7QNUNuJyUgnLhRcg0MTGrOQRHCLBeClfzUrMfVm5gDMHi5Qrsh1ATB5BHBdHDGbYL1zM883A8gWbL5VVFgu/iMfjds0DKPVm+DmtkI2gA4Qf6rqNyfidE/jO9y9DewaB9Ocfk+lZIeAht1kH+jQxekbzElPV1CYNI7KI0tIbrAX+7RuvNbBS/a6/VoWhST/syfCj/muuRxcr+hhSpMeEM0i+Fb4CUXfSfxYpUK1I3QMLn9gz7a1xGLfnJWzAjtgUNAxOx7GQ6Bb/QpxK0OBP79a/6W9UQA9IiyOJp7qG6bMiPdlOCscTM6SRFPNvcy0/fwLsHXZxlFxlgXmPWEwHQdI5hpUJ0dXYyaDuT68+7dVB0Vj55/sWnoExeAvn3uRW4y6gj8iINCQizbkpWWNiXqyddr3PjK48yQS5jWXt87+GhoykiDZKPOskH2DoEkP8qZJx6k3LKG1mR+fJKcgAzrV5p7q/dxbZkXrP1geJnWCvqH9ZPf2exMb1yoq+r8AEnrqCDtMYKUQJlzytT38j78L9gNVTgS9+94teIaKh0FkC3CnIHTeOc81y6kbxQBzGD/DywrdNtBL2DxUHRJ1oOgZ8RbGx4JT/fWM1q9d1X2EcUV5CakMsyjz5oxeCHFN4ZTbeHlBWWDFd2vv6TsNa/pK8v+GPa4UDQEAoUb8LQ82xZ/QMoFcecn5dGUGQk5qmkwJeyHgYv4BDcU3VliwFsURjoLimlN2104qXD565xfgRogOudj+IhHO6fQLs8spQkRCp1OzVB1Aj1TC8AdrqS9P9A8WL1h8SkTo4/nErbzJtWDKPRYLJqtn+iLoJhmWy4YV6YfTUZVsRciRtBvt4gGPKk9Yao4JUjB4cIuf2ppj8wCoTFR1AOjTwaMvyOz/r9rxwEvJTJhytiJXVqU/0BbkavsuCNED1wU1uHfy09424bf4d38lyfJtdyktGPu2lsQUO6WFA8MPb42o/4aZXUYhL7Ne1qWxCeb/svMGhdOLA/8MMQ3Qlo6ia59wjmBSgY5sdfIL76iWQWv0OdVoJutjDOwX6ybt8kBl1yJlOj+6SdNYyygOQ54D5a027RvRI5QU7WCyKQ/sQu33QAsB9pty+TMY4c0M2bb2UHrfUNo3eH+dYevcc/z940n5WsYliBUXRuAlTAIqBtfQwGHEypP7MOIyd+habuMSbfwI+NQJmFaDhift3xn7fRQjmF6ddPKHRoYlOWdymxoZ/pgYPrxUf9JhvpoKNWWiMDWimnNhoB2YN4oRKoXZmYohMJuQ1bPTZ/kyPu3bCslmYE9JQydAeyZY/EdFAFLgc2Q6zqL9YtKXXSBLHO9FFK08hvbSNyURuXTPaxk51/um49+fJHlF2/pD1sgdhrX1Ml6frA/+WQXbzd/2rZcJAuFxbCqbW7JUyWl1xdLT2RnLZbnSeuk6oR6iryHDAFC05l7XGibf7tiqIby0yQfY/9QOPfb+tggxf4kY61eNTg0rRoLkWZpHpmuLj7zhsOKbs6KxKsJtGg6dDwWTnF+zux5V7X8i5Z8EaTNzFT1fuEiYHgsGEi+q7/KRrkM1vPvBW/9kiud2NM4g5kASmKUOuaUGNXCmgbVVOt77oF+G4ZADJdyNgwOEvNigwVesEXWzpw9r7M70Xt4gi27Sx0utPe/Vk6PWoS2brSqDb+wXoYp1DvCnySfxF/DQ0VNCFKisGBE+pZWUR3tK5DZUibDJ9RldsB9/kTQFXp6QZY0zRf/cgq+q12Opnz68Z21I8fNQIHF1xJ+cvu5BPI4cdogmvR6rfQ4lQ/8/C/08HFBjTpsYrwg2BISDDAxxQAdGk0rE3rTDpkES24qJ09fT8qn6QnAwYLA88Du9TpBOnZvDFOXEIUppUyT4X90LmmUdF3NgbmM+4xeihmH3pCP7hPKJy6VLMbzVx7pGjJvKSuvNjFyEdfNpnQpR4ydsMdsK7/AGqb8roo14ikqvG8qr82CaFIYg76D3YJJM3y/2FuRXvR24Ut5LDkzbZLCGQYeTKB8FU3A2+WbOpNf3HJ2YqpYjoZM1Lb6XkqfAVjGBpCXgr0BUgpW6zEItKclUoRARmstYfU83lcCfHfoPo0cbBC4KmfPS6TqTtob9447EfJO2Lx2VzTZe91FgHj63QTiEBe6lpBLTft71FJbPGhWgIl2Vqz1V7c0/V/OhyeKzst1v4pIeKfP0jmC73hwEG+c87WU2HroIvqPWz+57mwHTROaijwNxsn0ssgzq5q4hCK5yq1okDpYTVTxmGfiDqWmCx3wTMWKSH26DeiAyAbJzj8OQrLVw9ns6oe09EBnEo3Q+IQPCZac2EqSAQkyLmgP4RYVS9whsw="
  JULIA_DEBUG: "Documenter"
