pages = ["index.md",
    "getting_started.md",
    "Tutorials" => Any["tutorials/parameter_estimation_ode.md",
                       "tutorials/direct_sensitivity.md",
                       "tutorials/adjoint_continuous_functional.md",
                       "tutorials/data_parallel.md",
                       "tutorials/chaotic_ode.md",
                       "Training Techniques and Tips" => Any["training_tips/local_minima.md",
                                                             "training_tips/divergence.md",
                                                             "training_tips/multiple_nn.md"]],
    "Examples" => Any["Ordinary Differential Equations (ODEs)" => Any["ode/exogenous_input.md",
                                                                      "ode/prediction_error_method.md",
                                                                      "ode/second_order_adjoints.md",
                                                                      "ode/second_order_neural.md"],
                      "Neural Ordinary Differential Equations (Neural ODE)" => Any["neural_ode/neural_ode_flux.md",
                                                                                   "neural_ode/simplechains.md",
                                                                                   "neural_ode/neural_gde.md",
                                                                                   "neural_ode/minibatch.md"],
                      "Stochastic Differential Equations (SDEs)" => Any["sde/optimization_sde.md",
                                                                        "sde/SDE_control.md"],
                      "Delay Differential Equations (DDEs)" => Any["dde/delay_diffeq.md"],
                      "Differential-Algebraic Equations (DAEs)" => Any["dae/physical_constraints.md"],
                      "Partial Differential Equations (PDEs)" => Any["pde/pde_constrained.md"],
                      "Hybrid and Jump Equations" => Any["hybrid_jump/hybrid_diffeq.md",
                                                         "hybrid_jump/bouncing_ball.md"],
                      "Bayesian Estimation" => Any["bayesian/turing_bayesian.md"],
                      "Optimal and Model Predictive Control" => Any["optimal_control/optimal_control.md",
                                                                    "optimal_control/feedback_control.md"]],
    "Manual and APIs" => Any["manual/differential_equation_sensitivities.md",
                             "manual/nonlinear_solve_sensitivities.md",
                             "manual/direct_forward_sensitivity.md",
                             "manual/direct_adjoint_sensitivities.md"],
    "Benchmarks" => "Benchmark.md",
    "Sensitivity Math Details" => "sensitivity_math.md",
]
