name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        group:
          - Core1
          - Core2
          - Core3
          - Core4
          - Core5
          - Core6
          - Core7
          - Core8
          - QA
          - SDE1
          - SDE2
          - SDE3
          - Callbacks1
          - Callbacks2
        version:
          - '1'
          - '1.11'
          - 'lts'
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      group: "${{ matrix.group }}"
      julia-version: "${{ matrix.version }}"
    secrets: "inherit"
