name: downstream_ci_diffeqflux
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
jobs:
  downstream_ci_diffeqflux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: julia -e 'import Pkg; Pkg.add(url="https://github.com/SciML/DiffEqSensitivity.jl",rev="master")'
      - run: julia -e 'import Pkg; Pkg.add("DiffEqFlux")'
      - run: julia -e 'import Pkg; Pkg.status()'
      - run: julia -e 'import Pkg; Pkg.test("DiffEqFlux")'
